version: "3.8"

services:
  springio-takehome2:
    image: springio-takehome2:1
    build:
      context: ../node-hello-master
      dockerfile: Dockerfile
    volumes:
      - /data/springio-takehome2
    ports:
      - "5433:5433"