version: "3.8"

services:
  springio-takehome2:
    image: springio-takehome2:13-alpine
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: takehome2
    build:
      context: ../node-hello-master
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data\
